### ISSUE TITLE
Request: Synchronous mode

### ISSUE THREAD

**Issue by bmulholland** [mizdra/graphql-codegen-typescript-fabbrica#86]
I saw [the comment about the difficulty of making a synchronous option for this library](https://github.com/mizdra/graphql-codegen-typescript-fabbrica/issues/74#issuecomment-2053615506), so I understand that this might not be feasible. Still, I wanted to log the request: top-level await isn't available in storybooks, particularly when taking snapshots for Chromatic. This means I have to jump through complex Storybook hoops of using `loaders` instead of standard args. It's a ton of boiler plate every time I use it, just to get the single `await`, and makes it really hard to override/set custom values per story. Would love a synchronous mode, it would really clean up our code.

**Comment by mizdra** [comment]
Thanks for sending a feature request!

> top-level await isn't available in storybooks

Is this true?  According to https://github.com/storybookjs/storybook/issues/15129 it seems possible. I actually tried it and was able to use top-level await.

- https://github.com/mizdra/storybook-top-level-await-test

Perhaps your bundler (vite, webpack, tubopack) is misconfigured. top-level await is only available for ES Modules-style code, Check that bundler outputs ES Modules style code.

On the other hand, it makes sense to provide an API like `buildSync()` for those who want to write code synchronously. Frankly, I'm not really willing to do it, since the workaround is to use top-level await. But if it's easy to implement, I'm willing to try.

**Comment by bmulholland** [comment]
Hm, good points, I'll look into why it's not working. Thanks! Closing for now.
